// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublisherData;

#nullable disable

namespace PublisherData.Migrations
{
    [DbContext(typeof(PubContext))]
    [Migration("20240322204536_SeedAuthors")]
    partial class SeedAuthors
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ArtistCover", b =>
                {
                    b.Property<int>("ArtistsArtistId")
                        .HasColumnType("int");

                    b.Property<int>("CoversCoverId")
                        .HasColumnType("int");

                    b.HasKey("ArtistsArtistId", "CoversCoverId");

                    b.HasIndex("CoversCoverId");

                    b.ToTable("ArtistCover");
                });

            modelBuilder.Entity("PublisherDomain.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("PublisherDomain.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            FirstName = "Johnson",
                            LastName = "Schmeler",
                            LastUpdated = new DateTime(2024, 3, 11, 7, 21, 32, 611, DateTimeKind.Local).AddTicks(2499)
                        },
                        new
                        {
                            AuthorId = 2,
                            FirstName = "Maud",
                            LastName = "Walter",
                            LastUpdated = new DateTime(2024, 3, 17, 7, 58, 38, 265, DateTimeKind.Local).AddTicks(6889)
                        },
                        new
                        {
                            AuthorId = 3,
                            FirstName = "Xander",
                            LastName = "Roob",
                            LastUpdated = new DateTime(2024, 2, 22, 10, 12, 12, 622, DateTimeKind.Local).AddTicks(1364)
                        },
                        new
                        {
                            AuthorId = 4,
                            FirstName = "Moses",
                            LastName = "Will",
                            LastUpdated = new DateTime(2024, 3, 13, 5, 29, 12, 822, DateTimeKind.Local).AddTicks(3226)
                        },
                        new
                        {
                            AuthorId = 5,
                            FirstName = "Rudolph",
                            LastName = "Hayes",
                            LastUpdated = new DateTime(2024, 2, 23, 15, 49, 14, 920, DateTimeKind.Local).AddTicks(3031)
                        },
                        new
                        {
                            AuthorId = 6,
                            FirstName = "Harry",
                            LastName = "Jakubowski",
                            LastUpdated = new DateTime(2024, 3, 14, 20, 21, 41, 736, DateTimeKind.Local).AddTicks(7347)
                        },
                        new
                        {
                            AuthorId = 7,
                            FirstName = "Kenya",
                            LastName = "Stokes",
                            LastUpdated = new DateTime(2024, 3, 20, 18, 22, 56, 592, DateTimeKind.Local).AddTicks(4639)
                        },
                        new
                        {
                            AuthorId = 8,
                            FirstName = "Elwyn",
                            LastName = "Kub",
                            LastUpdated = new DateTime(2024, 3, 10, 7, 11, 18, 857, DateTimeKind.Local).AddTicks(6687)
                        },
                        new
                        {
                            AuthorId = 9,
                            FirstName = "Zora",
                            LastName = "Beier",
                            LastUpdated = new DateTime(2024, 3, 13, 10, 57, 43, 895, DateTimeKind.Local).AddTicks(7482)
                        },
                        new
                        {
                            AuthorId = 10,
                            FirstName = "Terrence",
                            LastName = "Ward",
                            LastUpdated = new DateTime(2024, 3, 6, 8, 38, 58, 513, DateTimeKind.Local).AddTicks(6867)
                        },
                        new
                        {
                            AuthorId = 11,
                            FirstName = "Hazle",
                            LastName = "Bartell",
                            LastUpdated = new DateTime(2024, 3, 21, 9, 20, 0, 823, DateTimeKind.Local).AddTicks(3238)
                        },
                        new
                        {
                            AuthorId = 12,
                            FirstName = "Berenice",
                            LastName = "Lesch",
                            LastUpdated = new DateTime(2024, 3, 7, 2, 36, 54, 655, DateTimeKind.Local).AddTicks(8914)
                        },
                        new
                        {
                            AuthorId = 13,
                            FirstName = "Clement",
                            LastName = "Harvey",
                            LastUpdated = new DateTime(2024, 2, 22, 1, 59, 58, 553, DateTimeKind.Local).AddTicks(7026)
                        },
                        new
                        {
                            AuthorId = 14,
                            FirstName = "Kaela",
                            LastName = "Larkin",
                            LastUpdated = new DateTime(2024, 3, 20, 4, 45, 9, 957, DateTimeKind.Local).AddTicks(6783)
                        },
                        new
                        {
                            AuthorId = 15,
                            FirstName = "Stanford",
                            LastName = "Roberts",
                            LastUpdated = new DateTime(2024, 2, 23, 2, 39, 38, 793, DateTimeKind.Local).AddTicks(7028)
                        },
                        new
                        {
                            AuthorId = 16,
                            FirstName = "Reva",
                            LastName = "Beatty",
                            LastUpdated = new DateTime(2024, 2, 23, 14, 27, 58, 222, DateTimeKind.Local).AddTicks(934)
                        },
                        new
                        {
                            AuthorId = 17,
                            FirstName = "Lois",
                            LastName = "Reilly",
                            LastUpdated = new DateTime(2024, 3, 11, 13, 50, 29, 482, DateTimeKind.Local).AddTicks(2182)
                        },
                        new
                        {
                            AuthorId = 18,
                            FirstName = "Keeley",
                            LastName = "Leuschke",
                            LastUpdated = new DateTime(2024, 3, 8, 2, 17, 49, 642, DateTimeKind.Local).AddTicks(429)
                        },
                        new
                        {
                            AuthorId = 19,
                            FirstName = "Verla",
                            LastName = "D'Amore",
                            LastUpdated = new DateTime(2024, 3, 9, 14, 58, 36, 727, DateTimeKind.Local).AddTicks(2539)
                        },
                        new
                        {
                            AuthorId = 20,
                            FirstName = "Enid",
                            LastName = "Hoeger",
                            LastUpdated = new DateTime(2024, 2, 25, 19, 21, 9, 478, DateTimeKind.Local).AddTicks(9698)
                        },
                        new
                        {
                            AuthorId = 21,
                            FirstName = "Myah",
                            LastName = "Walker",
                            LastUpdated = new DateTime(2024, 3, 16, 11, 39, 33, 582, DateTimeKind.Local).AddTicks(7954)
                        },
                        new
                        {
                            AuthorId = 22,
                            FirstName = "Clinton",
                            LastName = "Schowalter",
                            LastUpdated = new DateTime(2024, 3, 6, 10, 3, 30, 395, DateTimeKind.Local).AddTicks(1542)
                        },
                        new
                        {
                            AuthorId = 23,
                            FirstName = "Garett",
                            LastName = "Labadie",
                            LastUpdated = new DateTime(2024, 3, 11, 20, 39, 31, 62, DateTimeKind.Local).AddTicks(4424)
                        },
                        new
                        {
                            AuthorId = 24,
                            FirstName = "Josie",
                            LastName = "Conn",
                            LastUpdated = new DateTime(2024, 3, 10, 21, 38, 30, 344, DateTimeKind.Local).AddTicks(5122)
                        },
                        new
                        {
                            AuthorId = 25,
                            FirstName = "Maximillia",
                            LastName = "Kassulke",
                            LastUpdated = new DateTime(2024, 3, 1, 10, 24, 21, 343, DateTimeKind.Local).AddTicks(5895)
                        },
                        new
                        {
                            AuthorId = 26,
                            FirstName = "Billy",
                            LastName = "Zboncak",
                            LastUpdated = new DateTime(2024, 3, 2, 10, 32, 30, 386, DateTimeKind.Local).AddTicks(7669)
                        },
                        new
                        {
                            AuthorId = 27,
                            FirstName = "Syble",
                            LastName = "Towne",
                            LastUpdated = new DateTime(2024, 3, 7, 14, 50, 43, 3, DateTimeKind.Local).AddTicks(9609)
                        },
                        new
                        {
                            AuthorId = 28,
                            FirstName = "Tavares",
                            LastName = "Armstrong",
                            LastUpdated = new DateTime(2024, 2, 23, 18, 26, 2, 989, DateTimeKind.Local).AddTicks(3382)
                        },
                        new
                        {
                            AuthorId = 29,
                            FirstName = "Dayton",
                            LastName = "Moen",
                            LastUpdated = new DateTime(2024, 3, 13, 6, 28, 17, 567, DateTimeKind.Local).AddTicks(4150)
                        },
                        new
                        {
                            AuthorId = 30,
                            FirstName = "Norene",
                            LastName = "Wolff",
                            LastUpdated = new DateTime(2024, 3, 22, 15, 1, 54, 932, DateTimeKind.Local).AddTicks(8625)
                        },
                        new
                        {
                            AuthorId = 31,
                            FirstName = "Mack",
                            LastName = "Goldner",
                            LastUpdated = new DateTime(2024, 3, 22, 4, 27, 42, 251, DateTimeKind.Local).AddTicks(1917)
                        },
                        new
                        {
                            AuthorId = 32,
                            FirstName = "Hanna",
                            LastName = "Howell",
                            LastUpdated = new DateTime(2024, 3, 1, 18, 46, 5, 638, DateTimeKind.Local).AddTicks(6993)
                        },
                        new
                        {
                            AuthorId = 33,
                            FirstName = "Rickie",
                            LastName = "McCullough",
                            LastUpdated = new DateTime(2024, 3, 21, 21, 32, 59, 500, DateTimeKind.Local).AddTicks(3731)
                        },
                        new
                        {
                            AuthorId = 34,
                            FirstName = "Dedric",
                            LastName = "Hudson",
                            LastUpdated = new DateTime(2024, 3, 6, 5, 33, 2, 901, DateTimeKind.Local).AddTicks(6856)
                        },
                        new
                        {
                            AuthorId = 35,
                            FirstName = "Daryl",
                            LastName = "Balistreri",
                            LastUpdated = new DateTime(2024, 2, 29, 16, 1, 23, 696, DateTimeKind.Local).AddTicks(7649)
                        },
                        new
                        {
                            AuthorId = 36,
                            FirstName = "Adan",
                            LastName = "Miller",
                            LastUpdated = new DateTime(2024, 2, 22, 15, 32, 0, 182, DateTimeKind.Local).AddTicks(9905)
                        },
                        new
                        {
                            AuthorId = 37,
                            FirstName = "Maxine",
                            LastName = "Lind",
                            LastUpdated = new DateTime(2024, 3, 6, 10, 13, 51, 102, DateTimeKind.Local).AddTicks(2516)
                        },
                        new
                        {
                            AuthorId = 38,
                            FirstName = "Devonte",
                            LastName = "Herzog",
                            LastUpdated = new DateTime(2024, 2, 26, 20, 28, 16, 40, DateTimeKind.Local).AddTicks(8039)
                        },
                        new
                        {
                            AuthorId = 39,
                            FirstName = "Domenic",
                            LastName = "Kulas",
                            LastUpdated = new DateTime(2024, 2, 27, 1, 32, 39, 486, DateTimeKind.Local).AddTicks(631)
                        },
                        new
                        {
                            AuthorId = 40,
                            FirstName = "Jabari",
                            LastName = "Jacobs",
                            LastUpdated = new DateTime(2024, 3, 8, 2, 1, 39, 59, DateTimeKind.Local).AddTicks(4637)
                        },
                        new
                        {
                            AuthorId = 41,
                            FirstName = "Sheila",
                            LastName = "Will",
                            LastUpdated = new DateTime(2024, 3, 12, 10, 41, 56, 148, DateTimeKind.Local).AddTicks(8173)
                        },
                        new
                        {
                            AuthorId = 42,
                            FirstName = "Lydia",
                            LastName = "Prosacco",
                            LastUpdated = new DateTime(2024, 3, 7, 10, 34, 1, 378, DateTimeKind.Local).AddTicks(2476)
                        },
                        new
                        {
                            AuthorId = 43,
                            FirstName = "Etha",
                            LastName = "Hintz",
                            LastUpdated = new DateTime(2024, 3, 3, 23, 30, 11, 332, DateTimeKind.Local).AddTicks(6856)
                        },
                        new
                        {
                            AuthorId = 44,
                            FirstName = "Emilia",
                            LastName = "Macejkovic",
                            LastUpdated = new DateTime(2024, 3, 9, 15, 47, 37, 522, DateTimeKind.Local).AddTicks(3388)
                        },
                        new
                        {
                            AuthorId = 45,
                            FirstName = "Norris",
                            LastName = "Cruickshank",
                            LastUpdated = new DateTime(2024, 3, 6, 12, 11, 36, 347, DateTimeKind.Local).AddTicks(3723)
                        },
                        new
                        {
                            AuthorId = 46,
                            FirstName = "Deanna",
                            LastName = "D'Amore",
                            LastUpdated = new DateTime(2024, 3, 22, 12, 13, 45, 474, DateTimeKind.Local).AddTicks(4794)
                        },
                        new
                        {
                            AuthorId = 47,
                            FirstName = "Luther",
                            LastName = "Frami",
                            LastUpdated = new DateTime(2024, 3, 21, 5, 39, 46, 354, DateTimeKind.Local).AddTicks(3783)
                        },
                        new
                        {
                            AuthorId = 48,
                            FirstName = "Carmine",
                            LastName = "Rowe",
                            LastUpdated = new DateTime(2024, 3, 21, 16, 43, 6, 264, DateTimeKind.Local).AddTicks(7700)
                        },
                        new
                        {
                            AuthorId = 49,
                            FirstName = "Filiberto",
                            LastName = "Frami",
                            LastUpdated = new DateTime(2024, 2, 23, 23, 29, 34, 667, DateTimeKind.Local).AddTicks(1533)
                        },
                        new
                        {
                            AuthorId = 50,
                            FirstName = "Shirley",
                            LastName = "Abshire",
                            LastUpdated = new DateTime(2024, 2, 29, 14, 11, 55, 48, DateTimeKind.Local).AddTicks(8288)
                        },
                        new
                        {
                            AuthorId = 51,
                            FirstName = "Kathlyn",
                            LastName = "Fahey",
                            LastUpdated = new DateTime(2024, 3, 20, 21, 48, 53, 756, DateTimeKind.Local).AddTicks(2654)
                        },
                        new
                        {
                            AuthorId = 52,
                            FirstName = "Kennedi",
                            LastName = "Luettgen",
                            LastUpdated = new DateTime(2024, 3, 5, 2, 14, 23, 82, DateTimeKind.Local).AddTicks(4394)
                        },
                        new
                        {
                            AuthorId = 53,
                            FirstName = "Percival",
                            LastName = "Murray",
                            LastUpdated = new DateTime(2024, 3, 6, 15, 52, 24, 154, DateTimeKind.Local).AddTicks(8694)
                        },
                        new
                        {
                            AuthorId = 54,
                            FirstName = "Deanna",
                            LastName = "Bailey",
                            LastUpdated = new DateTime(2024, 3, 6, 8, 6, 13, 33, DateTimeKind.Local).AddTicks(4810)
                        },
                        new
                        {
                            AuthorId = 55,
                            FirstName = "Christina",
                            LastName = "Leffler",
                            LastUpdated = new DateTime(2024, 2, 29, 20, 24, 33, 512, DateTimeKind.Local).AddTicks(5905)
                        },
                        new
                        {
                            AuthorId = 56,
                            FirstName = "Myrtis",
                            LastName = "Shanahan",
                            LastUpdated = new DateTime(2024, 2, 27, 3, 6, 16, 966, DateTimeKind.Local).AddTicks(4169)
                        },
                        new
                        {
                            AuthorId = 57,
                            FirstName = "Schuyler",
                            LastName = "Gorczany",
                            LastUpdated = new DateTime(2024, 3, 12, 8, 17, 2, 96, DateTimeKind.Local).AddTicks(688)
                        },
                        new
                        {
                            AuthorId = 58,
                            FirstName = "Cordie",
                            LastName = "Schuppe",
                            LastUpdated = new DateTime(2024, 2, 23, 20, 12, 57, 603, DateTimeKind.Local).AddTicks(1819)
                        },
                        new
                        {
                            AuthorId = 59,
                            FirstName = "Eldred",
                            LastName = "Gulgowski",
                            LastUpdated = new DateTime(2024, 3, 20, 3, 4, 38, 72, DateTimeKind.Local).AddTicks(6374)
                        },
                        new
                        {
                            AuthorId = 60,
                            FirstName = "Ofelia",
                            LastName = "Schmidt",
                            LastUpdated = new DateTime(2024, 3, 14, 8, 27, 37, 21, DateTimeKind.Local).AddTicks(9052)
                        },
                        new
                        {
                            AuthorId = 61,
                            FirstName = "Ashlee",
                            LastName = "Altenwerth",
                            LastUpdated = new DateTime(2024, 3, 8, 11, 47, 40, 742, DateTimeKind.Local).AddTicks(768)
                        },
                        new
                        {
                            AuthorId = 62,
                            FirstName = "Dean",
                            LastName = "Wilderman",
                            LastUpdated = new DateTime(2024, 2, 28, 3, 18, 41, 901, DateTimeKind.Local).AddTicks(4557)
                        },
                        new
                        {
                            AuthorId = 63,
                            FirstName = "Erica",
                            LastName = "Stroman",
                            LastUpdated = new DateTime(2024, 3, 7, 0, 27, 30, 281, DateTimeKind.Local).AddTicks(7982)
                        },
                        new
                        {
                            AuthorId = 64,
                            FirstName = "Ressie",
                            LastName = "Hartmann",
                            LastUpdated = new DateTime(2024, 3, 21, 15, 48, 54, 414, DateTimeKind.Local).AddTicks(5455)
                        },
                        new
                        {
                            AuthorId = 65,
                            FirstName = "Zelda",
                            LastName = "Haley",
                            LastUpdated = new DateTime(2024, 2, 23, 9, 24, 21, 984, DateTimeKind.Local).AddTicks(5538)
                        },
                        new
                        {
                            AuthorId = 66,
                            FirstName = "Darrell",
                            LastName = "Schinner",
                            LastUpdated = new DateTime(2024, 2, 28, 18, 37, 23, 993, DateTimeKind.Local).AddTicks(8873)
                        },
                        new
                        {
                            AuthorId = 67,
                            FirstName = "Edmund",
                            LastName = "Swaniawski",
                            LastUpdated = new DateTime(2024, 2, 21, 16, 6, 16, 373, DateTimeKind.Local).AddTicks(4366)
                        },
                        new
                        {
                            AuthorId = 68,
                            FirstName = "Demarco",
                            LastName = "Greenfelder",
                            LastUpdated = new DateTime(2024, 3, 5, 6, 39, 45, 103, DateTimeKind.Local).AddTicks(2948)
                        },
                        new
                        {
                            AuthorId = 69,
                            FirstName = "Derick",
                            LastName = "Nikolaus",
                            LastUpdated = new DateTime(2024, 3, 7, 12, 54, 42, 688, DateTimeKind.Local).AddTicks(7043)
                        },
                        new
                        {
                            AuthorId = 70,
                            FirstName = "Katelyn",
                            LastName = "Lebsack",
                            LastUpdated = new DateTime(2024, 2, 26, 14, 8, 15, 89, DateTimeKind.Local).AddTicks(4305)
                        },
                        new
                        {
                            AuthorId = 71,
                            FirstName = "Ariel",
                            LastName = "Leannon",
                            LastUpdated = new DateTime(2024, 3, 14, 18, 56, 21, 755, DateTimeKind.Local).AddTicks(6141)
                        },
                        new
                        {
                            AuthorId = 72,
                            FirstName = "Johnson",
                            LastName = "Hoppe",
                            LastUpdated = new DateTime(2024, 3, 11, 13, 40, 32, 745, DateTimeKind.Local).AddTicks(7864)
                        },
                        new
                        {
                            AuthorId = 73,
                            FirstName = "Davonte",
                            LastName = "Stark",
                            LastUpdated = new DateTime(2024, 2, 28, 5, 40, 45, 147, DateTimeKind.Local).AddTicks(7751)
                        },
                        new
                        {
                            AuthorId = 74,
                            FirstName = "Madonna",
                            LastName = "Labadie",
                            LastUpdated = new DateTime(2024, 2, 24, 1, 52, 5, 924, DateTimeKind.Local).AddTicks(4809)
                        },
                        new
                        {
                            AuthorId = 75,
                            FirstName = "Abelardo",
                            LastName = "Rowe",
                            LastUpdated = new DateTime(2024, 2, 25, 18, 1, 52, 91, DateTimeKind.Local).AddTicks(7906)
                        },
                        new
                        {
                            AuthorId = 76,
                            FirstName = "Ashley",
                            LastName = "Mills",
                            LastUpdated = new DateTime(2024, 3, 7, 18, 52, 59, 885, DateTimeKind.Local).AddTicks(8885)
                        },
                        new
                        {
                            AuthorId = 77,
                            FirstName = "Llewellyn",
                            LastName = "O'Kon",
                            LastUpdated = new DateTime(2024, 3, 16, 7, 33, 24, 502, DateTimeKind.Local).AddTicks(7731)
                        },
                        new
                        {
                            AuthorId = 78,
                            FirstName = "Autumn",
                            LastName = "Kozey",
                            LastUpdated = new DateTime(2024, 2, 21, 18, 20, 25, 436, DateTimeKind.Local).AddTicks(1048)
                        },
                        new
                        {
                            AuthorId = 79,
                            FirstName = "Jaunita",
                            LastName = "Vandervort",
                            LastUpdated = new DateTime(2024, 3, 10, 10, 51, 29, 34, DateTimeKind.Local).AddTicks(5007)
                        },
                        new
                        {
                            AuthorId = 80,
                            FirstName = "Susie",
                            LastName = "Mante",
                            LastUpdated = new DateTime(2024, 3, 10, 3, 53, 32, 684, DateTimeKind.Local).AddTicks(157)
                        },
                        new
                        {
                            AuthorId = 81,
                            FirstName = "Charity",
                            LastName = "Kiehn",
                            LastUpdated = new DateTime(2024, 3, 8, 21, 45, 37, 935, DateTimeKind.Local).AddTicks(8098)
                        },
                        new
                        {
                            AuthorId = 82,
                            FirstName = "Price",
                            LastName = "Sauer",
                            LastUpdated = new DateTime(2024, 3, 22, 2, 29, 14, 576, DateTimeKind.Local).AddTicks(7473)
                        },
                        new
                        {
                            AuthorId = 83,
                            FirstName = "Jaime",
                            LastName = "Kutch",
                            LastUpdated = new DateTime(2024, 3, 7, 3, 14, 27, 723, DateTimeKind.Local).AddTicks(8252)
                        },
                        new
                        {
                            AuthorId = 84,
                            FirstName = "Skye",
                            LastName = "Cormier",
                            LastUpdated = new DateTime(2024, 3, 19, 12, 14, 56, 7, DateTimeKind.Local).AddTicks(9411)
                        },
                        new
                        {
                            AuthorId = 85,
                            FirstName = "Darby",
                            LastName = "Kshlerin",
                            LastUpdated = new DateTime(2024, 3, 11, 10, 22, 54, 332, DateTimeKind.Local).AddTicks(2720)
                        },
                        new
                        {
                            AuthorId = 86,
                            FirstName = "Else",
                            LastName = "Hilpert",
                            LastUpdated = new DateTime(2024, 3, 1, 14, 47, 46, 173, DateTimeKind.Local).AddTicks(5857)
                        },
                        new
                        {
                            AuthorId = 87,
                            FirstName = "Laisha",
                            LastName = "Dooley",
                            LastUpdated = new DateTime(2024, 3, 2, 7, 35, 18, 451, DateTimeKind.Local).AddTicks(5473)
                        },
                        new
                        {
                            AuthorId = 88,
                            FirstName = "Flossie",
                            LastName = "Swift",
                            LastUpdated = new DateTime(2024, 2, 24, 2, 44, 6, 44, DateTimeKind.Local).AddTicks(9250)
                        },
                        new
                        {
                            AuthorId = 89,
                            FirstName = "Mariela",
                            LastName = "Parker",
                            LastUpdated = new DateTime(2024, 2, 27, 8, 47, 40, 310, DateTimeKind.Local).AddTicks(457)
                        },
                        new
                        {
                            AuthorId = 90,
                            FirstName = "Kailyn",
                            LastName = "Harvey",
                            LastUpdated = new DateTime(2024, 3, 14, 9, 20, 12, 995, DateTimeKind.Local).AddTicks(8832)
                        },
                        new
                        {
                            AuthorId = 91,
                            FirstName = "Golden",
                            LastName = "Stark",
                            LastUpdated = new DateTime(2024, 3, 12, 7, 45, 2, 21, DateTimeKind.Local).AddTicks(7261)
                        },
                        new
                        {
                            AuthorId = 92,
                            FirstName = "Nicole",
                            LastName = "Skiles",
                            LastUpdated = new DateTime(2024, 2, 26, 10, 42, 51, 561, DateTimeKind.Local).AddTicks(4743)
                        },
                        new
                        {
                            AuthorId = 93,
                            FirstName = "Amanda",
                            LastName = "Crist",
                            LastUpdated = new DateTime(2024, 3, 17, 6, 32, 4, 337, DateTimeKind.Local).AddTicks(5892)
                        },
                        new
                        {
                            AuthorId = 94,
                            FirstName = "Augustus",
                            LastName = "Krajcik",
                            LastUpdated = new DateTime(2024, 3, 17, 0, 56, 43, 373, DateTimeKind.Local).AddTicks(3994)
                        },
                        new
                        {
                            AuthorId = 95,
                            FirstName = "Kendall",
                            LastName = "Leuschke",
                            LastUpdated = new DateTime(2024, 3, 16, 1, 41, 6, 4, DateTimeKind.Local).AddTicks(4158)
                        },
                        new
                        {
                            AuthorId = 96,
                            FirstName = "Bernhard",
                            LastName = "Konopelski",
                            LastUpdated = new DateTime(2024, 2, 24, 19, 57, 34, 911, DateTimeKind.Local).AddTicks(747)
                        },
                        new
                        {
                            AuthorId = 97,
                            FirstName = "Angelina",
                            LastName = "Grady",
                            LastUpdated = new DateTime(2024, 2, 27, 19, 4, 38, 818, DateTimeKind.Local).AddTicks(2902)
                        },
                        new
                        {
                            AuthorId = 98,
                            FirstName = "Sierra",
                            LastName = "Satterfield",
                            LastUpdated = new DateTime(2024, 3, 1, 9, 46, 34, 382, DateTimeKind.Local).AddTicks(3543)
                        },
                        new
                        {
                            AuthorId = 99,
                            FirstName = "Marjolaine",
                            LastName = "Roberts",
                            LastUpdated = new DateTime(2024, 3, 19, 19, 22, 58, 292, DateTimeKind.Local).AddTicks(4751)
                        },
                        new
                        {
                            AuthorId = 100,
                            FirstName = "Queenie",
                            LastName = "Ferry",
                            LastUpdated = new DateTime(2024, 3, 11, 0, 41, 30, 621, DateTimeKind.Local).AddTicks(164)
                        });
                });

            modelBuilder.Entity("PublisherDomain.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("PublisherDomain.Cover", b =>
                {
                    b.Property<int>("CoverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoverId"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("DesignIdeas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DigitalOnly")
                        .HasColumnType("bit");

                    b.HasKey("CoverId");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("Covers");
                });

            modelBuilder.Entity("ArtistCover", b =>
                {
                    b.HasOne("PublisherDomain.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistsArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublisherDomain.Cover", null)
                        .WithMany()
                        .HasForeignKey("CoversCoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PublisherDomain.Book", b =>
                {
                    b.HasOne("PublisherDomain.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("PublisherDomain.Cover", b =>
                {
                    b.HasOne("PublisherDomain.Book", "Book")
                        .WithOne("Cover")
                        .HasForeignKey("PublisherDomain.Cover", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("PublisherDomain.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("PublisherDomain.Book", b =>
                {
                    b.Navigation("Cover")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
