// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublisherData;

#nullable disable

namespace PublisherData.Migrations
{
    [DbContext(typeof(PubContext))]
    [Migration("20240322211605_SeedBooks")]
    partial class SeedBooks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ArtistCover", b =>
                {
                    b.Property<int>("ArtistsArtistId")
                        .HasColumnType("int");

                    b.Property<int>("CoversCoverId")
                        .HasColumnType("int");

                    b.HasKey("ArtistsArtistId", "CoversCoverId");

                    b.HasIndex("CoversCoverId");

                    b.ToTable("ArtistCover");
                });

            modelBuilder.Entity("PublisherDomain.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("PublisherDomain.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            FirstName = "Esteban",
                            LastName = "Smitham",
                            LastUpdated = new DateTime(2024, 2, 29, 7, 32, 2, 327, DateTimeKind.Local).AddTicks(8996)
                        },
                        new
                        {
                            AuthorId = 2,
                            FirstName = "Queenie",
                            LastName = "Stanton",
                            LastUpdated = new DateTime(2024, 2, 24, 10, 0, 11, 190, DateTimeKind.Local).AddTicks(8463)
                        },
                        new
                        {
                            AuthorId = 3,
                            FirstName = "Sabryna",
                            LastName = "Blanda",
                            LastUpdated = new DateTime(2024, 3, 12, 0, 32, 34, 581, DateTimeKind.Local).AddTicks(553)
                        },
                        new
                        {
                            AuthorId = 4,
                            FirstName = "Queen",
                            LastName = "Dicki",
                            LastUpdated = new DateTime(2024, 3, 9, 11, 7, 20, 316, DateTimeKind.Local).AddTicks(9978)
                        },
                        new
                        {
                            AuthorId = 5,
                            FirstName = "Torey",
                            LastName = "McCullough",
                            LastUpdated = new DateTime(2024, 3, 2, 19, 3, 32, 987, DateTimeKind.Local).AddTicks(5543)
                        },
                        new
                        {
                            AuthorId = 6,
                            FirstName = "Hailie",
                            LastName = "Wolf",
                            LastUpdated = new DateTime(2024, 3, 12, 4, 24, 41, 677, DateTimeKind.Local).AddTicks(2081)
                        },
                        new
                        {
                            AuthorId = 7,
                            FirstName = "Shany",
                            LastName = "Leuschke",
                            LastUpdated = new DateTime(2024, 3, 19, 13, 0, 7, 894, DateTimeKind.Local).AddTicks(2066)
                        },
                        new
                        {
                            AuthorId = 8,
                            FirstName = "Valentine",
                            LastName = "Gibson",
                            LastUpdated = new DateTime(2024, 3, 2, 17, 23, 37, 521, DateTimeKind.Local).AddTicks(6393)
                        },
                        new
                        {
                            AuthorId = 9,
                            FirstName = "Joyce",
                            LastName = "Streich",
                            LastUpdated = new DateTime(2024, 3, 10, 21, 24, 40, 307, DateTimeKind.Local).AddTicks(9114)
                        },
                        new
                        {
                            AuthorId = 10,
                            FirstName = "Kariane",
                            LastName = "Gislason",
                            LastUpdated = new DateTime(2024, 3, 19, 5, 30, 32, 597, DateTimeKind.Local).AddTicks(2781)
                        },
                        new
                        {
                            AuthorId = 11,
                            FirstName = "Shemar",
                            LastName = "Ziemann",
                            LastUpdated = new DateTime(2024, 3, 20, 12, 27, 50, 711, DateTimeKind.Local).AddTicks(6133)
                        },
                        new
                        {
                            AuthorId = 12,
                            FirstName = "Ashlee",
                            LastName = "Schuster",
                            LastUpdated = new DateTime(2024, 2, 23, 17, 16, 31, 354, DateTimeKind.Local).AddTicks(869)
                        },
                        new
                        {
                            AuthorId = 13,
                            FirstName = "Dameon",
                            LastName = "Trantow",
                            LastUpdated = new DateTime(2024, 3, 13, 4, 5, 20, 441, DateTimeKind.Local).AddTicks(2604)
                        },
                        new
                        {
                            AuthorId = 14,
                            FirstName = "Tyrell",
                            LastName = "Gerhold",
                            LastUpdated = new DateTime(2024, 3, 13, 5, 28, 23, 868, DateTimeKind.Local).AddTicks(5606)
                        },
                        new
                        {
                            AuthorId = 15,
                            FirstName = "Birdie",
                            LastName = "Langworth",
                            LastUpdated = new DateTime(2024, 2, 23, 21, 59, 27, 305, DateTimeKind.Local).AddTicks(1280)
                        },
                        new
                        {
                            AuthorId = 16,
                            FirstName = "Gudrun",
                            LastName = "Hegmann",
                            LastUpdated = new DateTime(2024, 3, 18, 18, 53, 17, 566, DateTimeKind.Local).AddTicks(3718)
                        },
                        new
                        {
                            AuthorId = 17,
                            FirstName = "Katharina",
                            LastName = "Lakin",
                            LastUpdated = new DateTime(2024, 3, 4, 9, 25, 34, 331, DateTimeKind.Local).AddTicks(5934)
                        },
                        new
                        {
                            AuthorId = 18,
                            FirstName = "Dedrick",
                            LastName = "Thiel",
                            LastUpdated = new DateTime(2024, 3, 18, 4, 8, 45, 169, DateTimeKind.Local).AddTicks(5116)
                        },
                        new
                        {
                            AuthorId = 19,
                            FirstName = "Rocky",
                            LastName = "Schulist",
                            LastUpdated = new DateTime(2024, 3, 15, 2, 16, 30, 74, DateTimeKind.Local).AddTicks(3398)
                        },
                        new
                        {
                            AuthorId = 20,
                            FirstName = "Karli",
                            LastName = "Jakubowski",
                            LastUpdated = new DateTime(2024, 3, 9, 1, 36, 35, 187, DateTimeKind.Local).AddTicks(9124)
                        },
                        new
                        {
                            AuthorId = 21,
                            FirstName = "Callie",
                            LastName = "Grady",
                            LastUpdated = new DateTime(2024, 3, 19, 21, 51, 31, 53, DateTimeKind.Local).AddTicks(6555)
                        },
                        new
                        {
                            AuthorId = 22,
                            FirstName = "Evie",
                            LastName = "Wintheiser",
                            LastUpdated = new DateTime(2024, 3, 12, 0, 52, 31, 98, DateTimeKind.Local).AddTicks(5896)
                        },
                        new
                        {
                            AuthorId = 23,
                            FirstName = "Stephania",
                            LastName = "Moore",
                            LastUpdated = new DateTime(2024, 3, 21, 8, 33, 40, 75, DateTimeKind.Local).AddTicks(9706)
                        },
                        new
                        {
                            AuthorId = 24,
                            FirstName = "Arvid",
                            LastName = "Connelly",
                            LastUpdated = new DateTime(2024, 2, 27, 7, 52, 4, 887, DateTimeKind.Local).AddTicks(4778)
                        },
                        new
                        {
                            AuthorId = 25,
                            FirstName = "Hanna",
                            LastName = "Conroy",
                            LastUpdated = new DateTime(2024, 2, 28, 15, 8, 3, 287, DateTimeKind.Local).AddTicks(2732)
                        },
                        new
                        {
                            AuthorId = 26,
                            FirstName = "Rudolph",
                            LastName = "Wolf",
                            LastUpdated = new DateTime(2024, 3, 16, 12, 3, 14, 163, DateTimeKind.Local).AddTicks(3530)
                        },
                        new
                        {
                            AuthorId = 27,
                            FirstName = "Chris",
                            LastName = "O'Connell",
                            LastUpdated = new DateTime(2024, 3, 19, 19, 55, 20, 188, DateTimeKind.Local).AddTicks(7073)
                        },
                        new
                        {
                            AuthorId = 28,
                            FirstName = "Una",
                            LastName = "Hodkiewicz",
                            LastUpdated = new DateTime(2024, 3, 14, 22, 12, 6, 41, DateTimeKind.Local).AddTicks(7840)
                        },
                        new
                        {
                            AuthorId = 29,
                            FirstName = "Eryn",
                            LastName = "Williamson",
                            LastUpdated = new DateTime(2024, 2, 25, 23, 6, 42, 40, DateTimeKind.Local).AddTicks(896)
                        },
                        new
                        {
                            AuthorId = 30,
                            FirstName = "Ceasar",
                            LastName = "Kuphal",
                            LastUpdated = new DateTime(2024, 3, 9, 2, 44, 14, 444, DateTimeKind.Local).AddTicks(1719)
                        },
                        new
                        {
                            AuthorId = 31,
                            FirstName = "Lillian",
                            LastName = "Conroy",
                            LastUpdated = new DateTime(2024, 2, 26, 3, 19, 20, 125, DateTimeKind.Local).AddTicks(8061)
                        },
                        new
                        {
                            AuthorId = 32,
                            FirstName = "Sincere",
                            LastName = "Bechtelar",
                            LastUpdated = new DateTime(2024, 3, 7, 16, 46, 10, 293, DateTimeKind.Local).AddTicks(7180)
                        },
                        new
                        {
                            AuthorId = 33,
                            FirstName = "Polly",
                            LastName = "Witting",
                            LastUpdated = new DateTime(2024, 3, 20, 10, 45, 34, 951, DateTimeKind.Local).AddTicks(7841)
                        },
                        new
                        {
                            AuthorId = 34,
                            FirstName = "Cicero",
                            LastName = "McDermott",
                            LastUpdated = new DateTime(2024, 3, 10, 22, 49, 38, 370, DateTimeKind.Local).AddTicks(6699)
                        },
                        new
                        {
                            AuthorId = 35,
                            FirstName = "Daryl",
                            LastName = "Mohr",
                            LastUpdated = new DateTime(2024, 3, 7, 1, 3, 3, 522, DateTimeKind.Local).AddTicks(6002)
                        },
                        new
                        {
                            AuthorId = 36,
                            FirstName = "Jackie",
                            LastName = "Brakus",
                            LastUpdated = new DateTime(2024, 3, 2, 6, 57, 53, 186, DateTimeKind.Local).AddTicks(2154)
                        },
                        new
                        {
                            AuthorId = 37,
                            FirstName = "Gertrude",
                            LastName = "Grimes",
                            LastUpdated = new DateTime(2024, 2, 25, 6, 29, 59, 528, DateTimeKind.Local).AddTicks(4298)
                        },
                        new
                        {
                            AuthorId = 38,
                            FirstName = "Domenica",
                            LastName = "Erdman",
                            LastUpdated = new DateTime(2024, 3, 1, 7, 41, 32, 392, DateTimeKind.Local).AddTicks(3389)
                        },
                        new
                        {
                            AuthorId = 39,
                            FirstName = "Rocio",
                            LastName = "Sauer",
                            LastUpdated = new DateTime(2024, 3, 13, 17, 25, 39, 326, DateTimeKind.Local).AddTicks(3824)
                        },
                        new
                        {
                            AuthorId = 40,
                            FirstName = "Candelario",
                            LastName = "Daniel",
                            LastUpdated = new DateTime(2024, 3, 9, 1, 54, 58, 836, DateTimeKind.Local).AddTicks(1547)
                        },
                        new
                        {
                            AuthorId = 41,
                            FirstName = "Janae",
                            LastName = "Dietrich",
                            LastUpdated = new DateTime(2024, 3, 4, 1, 2, 55, 175, DateTimeKind.Local).AddTicks(3059)
                        },
                        new
                        {
                            AuthorId = 42,
                            FirstName = "Shanon",
                            LastName = "Bradtke",
                            LastUpdated = new DateTime(2024, 3, 18, 13, 59, 51, 146, DateTimeKind.Local).AddTicks(3642)
                        },
                        new
                        {
                            AuthorId = 43,
                            FirstName = "Mireille",
                            LastName = "Abshire",
                            LastUpdated = new DateTime(2024, 3, 17, 2, 49, 47, 125, DateTimeKind.Local).AddTicks(3588)
                        },
                        new
                        {
                            AuthorId = 44,
                            FirstName = "Taya",
                            LastName = "Larson",
                            LastUpdated = new DateTime(2024, 2, 26, 13, 16, 39, 987, DateTimeKind.Local).AddTicks(7050)
                        },
                        new
                        {
                            AuthorId = 45,
                            FirstName = "Lavina",
                            LastName = "Denesik",
                            LastUpdated = new DateTime(2024, 3, 3, 21, 18, 15, 991, DateTimeKind.Local).AddTicks(9412)
                        },
                        new
                        {
                            AuthorId = 46,
                            FirstName = "Addie",
                            LastName = "Rowe",
                            LastUpdated = new DateTime(2024, 3, 17, 4, 13, 52, 768, DateTimeKind.Local).AddTicks(1496)
                        },
                        new
                        {
                            AuthorId = 47,
                            FirstName = "Duncan",
                            LastName = "Witting",
                            LastUpdated = new DateTime(2024, 3, 6, 22, 42, 39, 579, DateTimeKind.Local).AddTicks(7056)
                        },
                        new
                        {
                            AuthorId = 48,
                            FirstName = "Gregoria",
                            LastName = "Graham",
                            LastUpdated = new DateTime(2024, 3, 8, 7, 31, 17, 898, DateTimeKind.Local).AddTicks(4347)
                        },
                        new
                        {
                            AuthorId = 49,
                            FirstName = "Ahmed",
                            LastName = "Ondricka",
                            LastUpdated = new DateTime(2024, 3, 16, 18, 9, 14, 213, DateTimeKind.Local).AddTicks(2389)
                        },
                        new
                        {
                            AuthorId = 50,
                            FirstName = "Watson",
                            LastName = "Larkin",
                            LastUpdated = new DateTime(2024, 2, 28, 19, 55, 8, 265, DateTimeKind.Local).AddTicks(5688)
                        },
                        new
                        {
                            AuthorId = 51,
                            FirstName = "Shanna",
                            LastName = "Kihn",
                            LastUpdated = new DateTime(2024, 3, 22, 10, 1, 53, 756, DateTimeKind.Local).AddTicks(3386)
                        },
                        new
                        {
                            AuthorId = 52,
                            FirstName = "Laurine",
                            LastName = "Zboncak",
                            LastUpdated = new DateTime(2024, 3, 7, 17, 50, 9, 579, DateTimeKind.Local).AddTicks(1289)
                        },
                        new
                        {
                            AuthorId = 53,
                            FirstName = "Rogelio",
                            LastName = "Strosin",
                            LastUpdated = new DateTime(2024, 3, 11, 4, 25, 6, 901, DateTimeKind.Local).AddTicks(7973)
                        },
                        new
                        {
                            AuthorId = 54,
                            FirstName = "Myriam",
                            LastName = "O'Keefe",
                            LastUpdated = new DateTime(2024, 2, 24, 20, 24, 31, 763, DateTimeKind.Local).AddTicks(5233)
                        },
                        new
                        {
                            AuthorId = 55,
                            FirstName = "Julio",
                            LastName = "West",
                            LastUpdated = new DateTime(2024, 3, 21, 14, 21, 32, 520, DateTimeKind.Local).AddTicks(8920)
                        },
                        new
                        {
                            AuthorId = 56,
                            FirstName = "Heloise",
                            LastName = "Crooks",
                            LastUpdated = new DateTime(2024, 2, 27, 14, 47, 49, 115, DateTimeKind.Local).AddTicks(1569)
                        },
                        new
                        {
                            AuthorId = 57,
                            FirstName = "Orland",
                            LastName = "O'Hara",
                            LastUpdated = new DateTime(2024, 2, 28, 23, 54, 58, 321, DateTimeKind.Local).AddTicks(3499)
                        },
                        new
                        {
                            AuthorId = 58,
                            FirstName = "Erick",
                            LastName = "Ruecker",
                            LastUpdated = new DateTime(2024, 2, 22, 14, 49, 49, 888, DateTimeKind.Local).AddTicks(6304)
                        },
                        new
                        {
                            AuthorId = 59,
                            FirstName = "Deron",
                            LastName = "Goyette",
                            LastUpdated = new DateTime(2024, 3, 6, 16, 27, 28, 755, DateTimeKind.Local).AddTicks(8000)
                        },
                        new
                        {
                            AuthorId = 60,
                            FirstName = "Kiarra",
                            LastName = "Kuhic",
                            LastUpdated = new DateTime(2024, 3, 8, 16, 59, 48, 231, DateTimeKind.Local).AddTicks(5348)
                        },
                        new
                        {
                            AuthorId = 61,
                            FirstName = "Florence",
                            LastName = "Windler",
                            LastUpdated = new DateTime(2024, 2, 21, 18, 3, 23, 5, DateTimeKind.Local).AddTicks(3664)
                        },
                        new
                        {
                            AuthorId = 62,
                            FirstName = "Autumn",
                            LastName = "Huel",
                            LastUpdated = new DateTime(2024, 2, 24, 16, 32, 32, 801, DateTimeKind.Local).AddTicks(3082)
                        },
                        new
                        {
                            AuthorId = 63,
                            FirstName = "Eugene",
                            LastName = "Hettinger",
                            LastUpdated = new DateTime(2024, 2, 28, 23, 41, 41, 804, DateTimeKind.Local).AddTicks(8042)
                        },
                        new
                        {
                            AuthorId = 64,
                            FirstName = "Marlen",
                            LastName = "Abernathy",
                            LastUpdated = new DateTime(2024, 3, 20, 23, 7, 27, 513, DateTimeKind.Local).AddTicks(9451)
                        },
                        new
                        {
                            AuthorId = 65,
                            FirstName = "Antonia",
                            LastName = "Oberbrunner",
                            LastUpdated = new DateTime(2024, 3, 19, 14, 16, 42, 817, DateTimeKind.Local).AddTicks(5709)
                        },
                        new
                        {
                            AuthorId = 66,
                            FirstName = "Wiley",
                            LastName = "Senger",
                            LastUpdated = new DateTime(2024, 3, 13, 1, 32, 27, 762, DateTimeKind.Local).AddTicks(5815)
                        },
                        new
                        {
                            AuthorId = 67,
                            FirstName = "Rhett",
                            LastName = "Osinski",
                            LastUpdated = new DateTime(2024, 2, 22, 0, 25, 57, 29, DateTimeKind.Local).AddTicks(1039)
                        },
                        new
                        {
                            AuthorId = 68,
                            FirstName = "Jewel",
                            LastName = "Volkman",
                            LastUpdated = new DateTime(2024, 3, 14, 19, 37, 15, 715, DateTimeKind.Local).AddTicks(6136)
                        },
                        new
                        {
                            AuthorId = 69,
                            FirstName = "Hermina",
                            LastName = "Stroman",
                            LastUpdated = new DateTime(2024, 3, 12, 22, 55, 16, 46, DateTimeKind.Local).AddTicks(88)
                        },
                        new
                        {
                            AuthorId = 70,
                            FirstName = "Thomas",
                            LastName = "Wisoky",
                            LastUpdated = new DateTime(2024, 2, 29, 16, 3, 30, 332, DateTimeKind.Local).AddTicks(4347)
                        },
                        new
                        {
                            AuthorId = 71,
                            FirstName = "Caesar",
                            LastName = "Hackett",
                            LastUpdated = new DateTime(2024, 3, 9, 17, 30, 18, 4, DateTimeKind.Local).AddTicks(4666)
                        },
                        new
                        {
                            AuthorId = 72,
                            FirstName = "Joe",
                            LastName = "Jacobs",
                            LastUpdated = new DateTime(2024, 3, 22, 8, 32, 51, 601, DateTimeKind.Local).AddTicks(7275)
                        },
                        new
                        {
                            AuthorId = 73,
                            FirstName = "Ruby",
                            LastName = "Grady",
                            LastUpdated = new DateTime(2024, 3, 3, 16, 21, 41, 182, DateTimeKind.Local).AddTicks(1247)
                        },
                        new
                        {
                            AuthorId = 74,
                            FirstName = "Elton",
                            LastName = "Gleason",
                            LastUpdated = new DateTime(2024, 3, 1, 11, 22, 28, 775, DateTimeKind.Local).AddTicks(1513)
                        },
                        new
                        {
                            AuthorId = 75,
                            FirstName = "Urban",
                            LastName = "Vandervort",
                            LastUpdated = new DateTime(2024, 2, 22, 13, 7, 16, 294, DateTimeKind.Local).AddTicks(1114)
                        },
                        new
                        {
                            AuthorId = 76,
                            FirstName = "Alia",
                            LastName = "Kuvalis",
                            LastUpdated = new DateTime(2024, 3, 9, 6, 57, 34, 483, DateTimeKind.Local).AddTicks(8338)
                        },
                        new
                        {
                            AuthorId = 77,
                            FirstName = "Samara",
                            LastName = "Simonis",
                            LastUpdated = new DateTime(2024, 3, 20, 17, 40, 59, 87, DateTimeKind.Local).AddTicks(8220)
                        },
                        new
                        {
                            AuthorId = 78,
                            FirstName = "Jazlyn",
                            LastName = "Bayer",
                            LastUpdated = new DateTime(2024, 3, 1, 20, 48, 18, 870, DateTimeKind.Local).AddTicks(5752)
                        },
                        new
                        {
                            AuthorId = 79,
                            FirstName = "Gaetano",
                            LastName = "Krajcik",
                            LastUpdated = new DateTime(2024, 2, 29, 4, 10, 15, 482, DateTimeKind.Local).AddTicks(7316)
                        },
                        new
                        {
                            AuthorId = 80,
                            FirstName = "Ewald",
                            LastName = "Howell",
                            LastUpdated = new DateTime(2024, 3, 22, 1, 7, 47, 949, DateTimeKind.Local).AddTicks(6526)
                        },
                        new
                        {
                            AuthorId = 81,
                            FirstName = "Geoffrey",
                            LastName = "Weimann",
                            LastUpdated = new DateTime(2024, 3, 14, 7, 37, 28, 724, DateTimeKind.Local).AddTicks(1597)
                        },
                        new
                        {
                            AuthorId = 82,
                            FirstName = "Kim",
                            LastName = "Collins",
                            LastUpdated = new DateTime(2024, 3, 15, 16, 5, 38, 232, DateTimeKind.Local).AddTicks(8985)
                        },
                        new
                        {
                            AuthorId = 83,
                            FirstName = "Janessa",
                            LastName = "Dooley",
                            LastUpdated = new DateTime(2024, 2, 22, 2, 50, 16, 279, DateTimeKind.Local).AddTicks(4292)
                        },
                        new
                        {
                            AuthorId = 84,
                            FirstName = "Fannie",
                            LastName = "Jacobi",
                            LastUpdated = new DateTime(2024, 3, 7, 23, 7, 4, 413, DateTimeKind.Local).AddTicks(9034)
                        },
                        new
                        {
                            AuthorId = 85,
                            FirstName = "Danika",
                            LastName = "Quitzon",
                            LastUpdated = new DateTime(2024, 2, 22, 7, 46, 27, 248, DateTimeKind.Local).AddTicks(5001)
                        },
                        new
                        {
                            AuthorId = 86,
                            FirstName = "Lisa",
                            LastName = "Rath",
                            LastUpdated = new DateTime(2024, 3, 19, 19, 37, 14, 575, DateTimeKind.Local).AddTicks(5875)
                        },
                        new
                        {
                            AuthorId = 87,
                            FirstName = "Kayley",
                            LastName = "Schoen",
                            LastUpdated = new DateTime(2024, 2, 28, 23, 13, 3, 173, DateTimeKind.Local).AddTicks(4426)
                        },
                        new
                        {
                            AuthorId = 88,
                            FirstName = "Ford",
                            LastName = "Nolan",
                            LastUpdated = new DateTime(2024, 3, 1, 22, 40, 47, 162, DateTimeKind.Local).AddTicks(1924)
                        },
                        new
                        {
                            AuthorId = 89,
                            FirstName = "Benedict",
                            LastName = "Welch",
                            LastUpdated = new DateTime(2024, 3, 13, 16, 12, 42, 975, DateTimeKind.Local).AddTicks(6877)
                        },
                        new
                        {
                            AuthorId = 90,
                            FirstName = "Gina",
                            LastName = "Senger",
                            LastUpdated = new DateTime(2024, 3, 14, 11, 42, 55, 158, DateTimeKind.Local).AddTicks(2935)
                        },
                        new
                        {
                            AuthorId = 91,
                            FirstName = "Emilia",
                            LastName = "Shields",
                            LastUpdated = new DateTime(2024, 3, 19, 8, 7, 0, 571, DateTimeKind.Local).AddTicks(228)
                        },
                        new
                        {
                            AuthorId = 92,
                            FirstName = "Harley",
                            LastName = "Hodkiewicz",
                            LastUpdated = new DateTime(2024, 3, 6, 17, 16, 14, 457, DateTimeKind.Local).AddTicks(4516)
                        },
                        new
                        {
                            AuthorId = 93,
                            FirstName = "Hiram",
                            LastName = "McGlynn",
                            LastUpdated = new DateTime(2024, 3, 3, 17, 2, 6, 869, DateTimeKind.Local).AddTicks(6478)
                        },
                        new
                        {
                            AuthorId = 94,
                            FirstName = "Evelyn",
                            LastName = "Dooley",
                            LastUpdated = new DateTime(2024, 3, 12, 1, 23, 18, 584, DateTimeKind.Local).AddTicks(2655)
                        },
                        new
                        {
                            AuthorId = 95,
                            FirstName = "Lori",
                            LastName = "Macejkovic",
                            LastUpdated = new DateTime(2024, 3, 14, 22, 59, 2, 885, DateTimeKind.Local).AddTicks(2506)
                        },
                        new
                        {
                            AuthorId = 96,
                            FirstName = "Liza",
                            LastName = "West",
                            LastUpdated = new DateTime(2024, 3, 1, 4, 10, 8, 142, DateTimeKind.Local).AddTicks(876)
                        },
                        new
                        {
                            AuthorId = 97,
                            FirstName = "Terrell",
                            LastName = "Wilderman",
                            LastUpdated = new DateTime(2024, 3, 19, 14, 20, 45, 446, DateTimeKind.Local).AddTicks(2783)
                        },
                        new
                        {
                            AuthorId = 98,
                            FirstName = "Mireya",
                            LastName = "Jast",
                            LastUpdated = new DateTime(2024, 3, 9, 0, 0, 10, 601, DateTimeKind.Local).AddTicks(6580)
                        },
                        new
                        {
                            AuthorId = 99,
                            FirstName = "Frances",
                            LastName = "Denesik",
                            LastUpdated = new DateTime(2024, 2, 23, 10, 12, 51, 760, DateTimeKind.Local).AddTicks(3732)
                        },
                        new
                        {
                            AuthorId = 100,
                            FirstName = "Lori",
                            LastName = "Heller",
                            LastUpdated = new DateTime(2024, 2, 26, 7, 29, 32, 445, DateTimeKind.Local).AddTicks(8524)
                        });
                });

            modelBuilder.Entity("PublisherDomain.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 25,
                            BasePrice = 60.885423972223275m,
                            PublishDate = new DateTime(2022, 9, 12, 8, 13, 5, 193, DateTimeKind.Local).AddTicks(1398),
                            Title = "transition robust e-markets"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 90,
                            BasePrice = 51.714200538699345m,
                            PublishDate = new DateTime(2023, 5, 2, 2, 50, 29, 512, DateTimeKind.Local).AddTicks(9190),
                            Title = "aggregate back-end synergies"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 63,
                            BasePrice = 36.326879413568765m,
                            PublishDate = new DateTime(2020, 5, 16, 17, 25, 44, 368, DateTimeKind.Local).AddTicks(1537),
                            Title = "transform world-class synergies"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 47,
                            BasePrice = 75.789107054461020m,
                            PublishDate = new DateTime(2020, 10, 3, 7, 40, 5, 344, DateTimeKind.Local).AddTicks(7134),
                            Title = "disintermediate magnetic users"
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 26,
                            BasePrice = 25.625221708531165m,
                            PublishDate = new DateTime(2017, 3, 4, 17, 13, 33, 572, DateTimeKind.Local).AddTicks(3812),
                            Title = "expedite holistic initiatives"
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 11,
                            BasePrice = 53.212348043261290m,
                            PublishDate = new DateTime(2018, 4, 16, 0, 40, 44, 790, DateTimeKind.Local).AddTicks(1378),
                            Title = "brand visionary convergence"
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 62,
                            BasePrice = 95.304495786126580m,
                            PublishDate = new DateTime(2019, 8, 15, 21, 39, 23, 586, DateTimeKind.Local).AddTicks(2928),
                            Title = "strategize e-business metrics"
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 91,
                            BasePrice = 89.412406085671175m,
                            PublishDate = new DateTime(2021, 11, 14, 5, 54, 38, 411, DateTimeKind.Local).AddTicks(602),
                            Title = "whiteboard cross-platform e-commerce"
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 37,
                            BasePrice = 38.616421654110840m,
                            PublishDate = new DateTime(2019, 10, 7, 12, 42, 51, 743, DateTimeKind.Local).AddTicks(5441),
                            Title = "integrate proactive vortals"
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 62,
                            BasePrice = 73.041568354603140m,
                            PublishDate = new DateTime(2023, 7, 10, 20, 25, 31, 324, DateTimeKind.Local).AddTicks(7745),
                            Title = "recontextualize sexy architectures"
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 85,
                            BasePrice = 14.535031600282575m,
                            PublishDate = new DateTime(2023, 9, 3, 9, 9, 44, 459, DateTimeKind.Local).AddTicks(4824),
                            Title = "envisioneer cross-platform experiences"
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 20,
                            BasePrice = 25.099523255942875m,
                            PublishDate = new DateTime(2016, 12, 7, 11, 29, 8, 739, DateTimeKind.Local).AddTicks(510),
                            Title = "brand leading-edge platforms"
                        },
                        new
                        {
                            BookId = 13,
                            AuthorId = 37,
                            BasePrice = 75.828712116217090m,
                            PublishDate = new DateTime(2023, 11, 8, 11, 44, 28, 894, DateTimeKind.Local).AddTicks(5966),
                            Title = "leverage enterprise initiatives"
                        },
                        new
                        {
                            BookId = 14,
                            AuthorId = 89,
                            BasePrice = 11.186097820464195m,
                            PublishDate = new DateTime(2019, 7, 24, 16, 36, 19, 209, DateTimeKind.Local).AddTicks(9706),
                            Title = "incentivize B2C action-items"
                        },
                        new
                        {
                            BookId = 15,
                            AuthorId = 63,
                            BasePrice = 48.284445162498235m,
                            PublishDate = new DateTime(2019, 10, 9, 5, 45, 1, 408, DateTimeKind.Local).AddTicks(5519),
                            Title = "matrix real-time metrics"
                        },
                        new
                        {
                            BookId = 16,
                            AuthorId = 81,
                            BasePrice = 88.219007648847335m,
                            PublishDate = new DateTime(2022, 9, 8, 21, 53, 20, 303, DateTimeKind.Local).AddTicks(1214),
                            Title = "evolve killer applications"
                        },
                        new
                        {
                            BookId = 17,
                            AuthorId = 26,
                            BasePrice = 45.95703266729720m,
                            PublishDate = new DateTime(2016, 12, 18, 15, 40, 2, 570, DateTimeKind.Local).AddTicks(1550),
                            Title = "visualize B2B portals"
                        },
                        new
                        {
                            BookId = 18,
                            AuthorId = 74,
                            BasePrice = 25.993848286950110m,
                            PublishDate = new DateTime(2014, 5, 29, 13, 21, 41, 57, DateTimeKind.Local).AddTicks(2583),
                            Title = "utilize B2B synergies"
                        },
                        new
                        {
                            BookId = 19,
                            AuthorId = 44,
                            BasePrice = 20.830353369712155m,
                            PublishDate = new DateTime(2019, 3, 6, 15, 40, 1, 405, DateTimeKind.Local).AddTicks(136),
                            Title = "envisioneer robust channels"
                        },
                        new
                        {
                            BookId = 20,
                            AuthorId = 54,
                            BasePrice = 13.9206945229349235m,
                            PublishDate = new DateTime(2023, 4, 10, 12, 11, 57, 406, DateTimeKind.Local).AddTicks(9285),
                            Title = "transform cross-media infomediaries"
                        },
                        new
                        {
                            BookId = 21,
                            AuthorId = 7,
                            BasePrice = 94.902997778534380m,
                            PublishDate = new DateTime(2019, 2, 7, 20, 25, 16, 185, DateTimeKind.Local).AddTicks(2467),
                            Title = "visualize integrated functionalities"
                        },
                        new
                        {
                            BookId = 22,
                            AuthorId = 6,
                            BasePrice = 94.660404042693335m,
                            PublishDate = new DateTime(2023, 11, 29, 16, 46, 54, 476, DateTimeKind.Local).AddTicks(2589),
                            Title = "recontextualize innovative e-markets"
                        },
                        new
                        {
                            BookId = 23,
                            AuthorId = 17,
                            BasePrice = 49.816595646968585m,
                            PublishDate = new DateTime(2019, 6, 30, 9, 16, 33, 31, DateTimeKind.Local).AddTicks(2436),
                            Title = "optimize frictionless action-items"
                        },
                        new
                        {
                            BookId = 24,
                            AuthorId = 46,
                            BasePrice = 87.388365141321330m,
                            PublishDate = new DateTime(2022, 7, 6, 16, 3, 56, 836, DateTimeKind.Local).AddTicks(9580),
                            Title = "drive holistic supply-chains"
                        },
                        new
                        {
                            BookId = 25,
                            AuthorId = 12,
                            BasePrice = 55.437353088385635m,
                            PublishDate = new DateTime(2015, 7, 22, 21, 2, 11, 809, DateTimeKind.Local).AddTicks(7182),
                            Title = "maximize innovative partnerships"
                        },
                        new
                        {
                            BookId = 26,
                            AuthorId = 65,
                            BasePrice = 96.62613368187715m,
                            PublishDate = new DateTime(2019, 12, 1, 14, 26, 18, 272, DateTimeKind.Local).AddTicks(5698),
                            Title = "scale strategic portals"
                        },
                        new
                        {
                            BookId = 27,
                            AuthorId = 70,
                            BasePrice = 88.521472572070885m,
                            PublishDate = new DateTime(2018, 4, 27, 16, 44, 33, 466, DateTimeKind.Local).AddTicks(7949),
                            Title = "whiteboard next-generation interfaces"
                        },
                        new
                        {
                            BookId = 28,
                            AuthorId = 9,
                            BasePrice = 90.707729591327065m,
                            PublishDate = new DateTime(2023, 10, 21, 16, 14, 50, 51, DateTimeKind.Local).AddTicks(5068),
                            Title = "strategize seamless relationships"
                        },
                        new
                        {
                            BookId = 29,
                            AuthorId = 50,
                            BasePrice = 68.9373457595795m,
                            PublishDate = new DateTime(2021, 10, 1, 9, 44, 28, 26, DateTimeKind.Local).AddTicks(4353),
                            Title = "brand collaborative web-readiness"
                        },
                        new
                        {
                            BookId = 30,
                            AuthorId = 73,
                            BasePrice = 97.488270684259895m,
                            PublishDate = new DateTime(2023, 2, 25, 18, 32, 42, 913, DateTimeKind.Local).AddTicks(2629),
                            Title = "facilitate ubiquitous initiatives"
                        },
                        new
                        {
                            BookId = 31,
                            AuthorId = 24,
                            BasePrice = 86.573369370598595m,
                            PublishDate = new DateTime(2019, 7, 10, 2, 56, 47, 250, DateTimeKind.Local).AddTicks(5439),
                            Title = "integrate open-source niches"
                        },
                        new
                        {
                            BookId = 32,
                            AuthorId = 59,
                            BasePrice = 68.390668078959420m,
                            PublishDate = new DateTime(2014, 8, 16, 8, 44, 18, 185, DateTimeKind.Local).AddTicks(5427),
                            Title = "e-enable value-added e-commerce"
                        },
                        new
                        {
                            BookId = 33,
                            AuthorId = 83,
                            BasePrice = 44.579563127941685m,
                            PublishDate = new DateTime(2024, 3, 14, 13, 0, 42, 221, DateTimeKind.Local).AddTicks(619),
                            Title = "innovate 24/7 web services"
                        },
                        new
                        {
                            BookId = 34,
                            AuthorId = 19,
                            BasePrice = 42.055688650065380m,
                            PublishDate = new DateTime(2019, 8, 22, 10, 54, 15, 225, DateTimeKind.Local).AddTicks(900),
                            Title = "empower magnetic web services"
                        },
                        new
                        {
                            BookId = 35,
                            AuthorId = 16,
                            BasePrice = 90.418158963482315m,
                            PublishDate = new DateTime(2018, 3, 27, 6, 22, 30, 596, DateTimeKind.Local).AddTicks(9610),
                            Title = "incentivize vertical mindshare"
                        },
                        new
                        {
                            BookId = 36,
                            AuthorId = 85,
                            BasePrice = 30.563409303953955m,
                            PublishDate = new DateTime(2015, 12, 18, 11, 35, 45, 87, DateTimeKind.Local).AddTicks(1658),
                            Title = "extend killer solutions"
                        },
                        new
                        {
                            BookId = 37,
                            AuthorId = 91,
                            BasePrice = 67.874567274316675m,
                            PublishDate = new DateTime(2015, 8, 4, 8, 12, 16, 297, DateTimeKind.Local).AddTicks(7473),
                            Title = "integrate dynamic deliverables"
                        },
                        new
                        {
                            BookId = 38,
                            AuthorId = 13,
                            BasePrice = 60.404938700989180m,
                            PublishDate = new DateTime(2016, 12, 10, 23, 59, 35, 301, DateTimeKind.Local).AddTicks(3621),
                            Title = "implement one-to-one portals"
                        },
                        new
                        {
                            BookId = 39,
                            AuthorId = 61,
                            BasePrice = 50.016212015441990m,
                            PublishDate = new DateTime(2018, 1, 5, 4, 51, 43, 137, DateTimeKind.Local).AddTicks(7643),
                            Title = "reintermediate sticky e-commerce"
                        },
                        new
                        {
                            BookId = 40,
                            AuthorId = 54,
                            BasePrice = 80.957925711293510m,
                            PublishDate = new DateTime(2018, 2, 1, 23, 59, 24, 295, DateTimeKind.Local).AddTicks(4314),
                            Title = "drive turn-key networks"
                        },
                        new
                        {
                            BookId = 41,
                            AuthorId = 47,
                            BasePrice = 39.218254727676530m,
                            PublishDate = new DateTime(2017, 3, 25, 6, 25, 33, 7, DateTimeKind.Local).AddTicks(4022),
                            Title = "matrix revolutionary infrastructures"
                        },
                        new
                        {
                            BookId = 42,
                            AuthorId = 13,
                            BasePrice = 48.915757656156215m,
                            PublishDate = new DateTime(2016, 8, 20, 3, 31, 57, 219, DateTimeKind.Local).AddTicks(1496),
                            Title = "synthesize user-centric schemas"
                        },
                        new
                        {
                            BookId = 43,
                            AuthorId = 29,
                            BasePrice = 55.14503062322835m,
                            PublishDate = new DateTime(2017, 3, 4, 6, 19, 24, 636, DateTimeKind.Local).AddTicks(3037),
                            Title = "maximize transparent eyeballs"
                        },
                        new
                        {
                            BookId = 44,
                            AuthorId = 20,
                            BasePrice = 11.0728488186627390m,
                            PublishDate = new DateTime(2023, 1, 24, 8, 57, 42, 581, DateTimeKind.Local).AddTicks(435),
                            Title = "repurpose seamless e-markets"
                        },
                        new
                        {
                            BookId = 45,
                            AuthorId = 61,
                            BasePrice = 45.158815778058870m,
                            PublishDate = new DateTime(2022, 9, 15, 6, 6, 57, 113, DateTimeKind.Local).AddTicks(5426),
                            Title = "aggregate turn-key networks"
                        },
                        new
                        {
                            BookId = 46,
                            AuthorId = 12,
                            BasePrice = 63.930270225874910m,
                            PublishDate = new DateTime(2017, 9, 8, 1, 16, 40, 283, DateTimeKind.Local).AddTicks(611),
                            Title = "utilize bricks-and-clicks e-services"
                        },
                        new
                        {
                            BookId = 47,
                            AuthorId = 27,
                            BasePrice = 78.568451723305390m,
                            PublishDate = new DateTime(2014, 7, 6, 15, 49, 27, 967, DateTimeKind.Local).AddTicks(8634),
                            Title = "productize intuitive action-items"
                        },
                        new
                        {
                            BookId = 48,
                            AuthorId = 93,
                            BasePrice = 8.7330749910065520m,
                            PublishDate = new DateTime(2014, 4, 24, 10, 20, 46, 485, DateTimeKind.Local).AddTicks(869),
                            Title = "generate innovative e-business"
                        },
                        new
                        {
                            BookId = 49,
                            AuthorId = 97,
                            BasePrice = 20.585401467901130m,
                            PublishDate = new DateTime(2020, 10, 13, 17, 34, 48, 494, DateTimeKind.Local).AddTicks(8693),
                            Title = "evolve rich experiences"
                        },
                        new
                        {
                            BookId = 50,
                            AuthorId = 96,
                            BasePrice = 51.650695548754955m,
                            PublishDate = new DateTime(2018, 2, 11, 6, 29, 48, 512, DateTimeKind.Local).AddTicks(3992),
                            Title = "grow proactive applications"
                        },
                        new
                        {
                            BookId = 51,
                            AuthorId = 85,
                            BasePrice = 87.967713687618640m,
                            PublishDate = new DateTime(2018, 1, 20, 21, 22, 15, 713, DateTimeKind.Local).AddTicks(6060),
                            Title = "reinvent robust users"
                        },
                        new
                        {
                            BookId = 52,
                            AuthorId = 32,
                            BasePrice = 37.952273037774815m,
                            PublishDate = new DateTime(2023, 12, 15, 3, 42, 30, 791, DateTimeKind.Local).AddTicks(3458),
                            Title = "cultivate mission-critical schemas"
                        },
                        new
                        {
                            BookId = 53,
                            AuthorId = 11,
                            BasePrice = 11.3512016213436475m,
                            PublishDate = new DateTime(2018, 4, 27, 13, 37, 25, 874, DateTimeKind.Local).AddTicks(3178),
                            Title = "utilize 24/365 infrastructures"
                        },
                        new
                        {
                            BookId = 54,
                            AuthorId = 86,
                            BasePrice = 74.739878044094115m,
                            PublishDate = new DateTime(2015, 3, 16, 19, 30, 3, 942, DateTimeKind.Local).AddTicks(1166),
                            Title = "transform transparent action-items"
                        },
                        new
                        {
                            BookId = 55,
                            AuthorId = 17,
                            BasePrice = 30.195499485729070m,
                            PublishDate = new DateTime(2021, 8, 9, 16, 15, 6, 906, DateTimeKind.Local).AddTicks(6729),
                            Title = "unleash distributed metrics"
                        },
                        new
                        {
                            BookId = 56,
                            AuthorId = 78,
                            BasePrice = 42.0440298858825m,
                            PublishDate = new DateTime(2014, 3, 28, 22, 18, 0, 86, DateTimeKind.Local).AddTicks(8501),
                            Title = "brand transparent markets"
                        },
                        new
                        {
                            BookId = 57,
                            AuthorId = 1,
                            BasePrice = 6.0508698074255180m,
                            PublishDate = new DateTime(2018, 5, 9, 15, 0, 14, 299, DateTimeKind.Local).AddTicks(8213),
                            Title = "utilize user-centric synergies"
                        },
                        new
                        {
                            BookId = 58,
                            AuthorId = 50,
                            BasePrice = 65.63554667300205m,
                            PublishDate = new DateTime(2019, 4, 30, 17, 34, 5, 162, DateTimeKind.Local).AddTicks(5038),
                            Title = "whiteboard e-business experiences"
                        },
                        new
                        {
                            BookId = 59,
                            AuthorId = 47,
                            BasePrice = 72.96824286085785m,
                            PublishDate = new DateTime(2023, 6, 4, 22, 10, 59, 255, DateTimeKind.Local).AddTicks(6439),
                            Title = "deliver e-business applications"
                        },
                        new
                        {
                            BookId = 60,
                            AuthorId = 37,
                            BasePrice = 90.895893699022340m,
                            PublishDate = new DateTime(2015, 5, 2, 1, 4, 8, 772, DateTimeKind.Local).AddTicks(5409),
                            Title = "whiteboard world-class mindshare"
                        },
                        new
                        {
                            BookId = 61,
                            AuthorId = 35,
                            BasePrice = 71.818054571351825m,
                            PublishDate = new DateTime(2017, 6, 28, 21, 11, 43, 313, DateTimeKind.Local).AddTicks(9634),
                            Title = "transform killer networks"
                        },
                        new
                        {
                            BookId = 62,
                            AuthorId = 28,
                            BasePrice = 88.102630384108420m,
                            PublishDate = new DateTime(2022, 6, 12, 21, 9, 26, 538, DateTimeKind.Local).AddTicks(5374),
                            Title = "synergize sticky infrastructures"
                        },
                        new
                        {
                            BookId = 63,
                            AuthorId = 48,
                            BasePrice = 26.351250477164005m,
                            PublishDate = new DateTime(2017, 6, 3, 2, 0, 51, 701, DateTimeKind.Local).AddTicks(5095),
                            Title = "facilitate cutting-edge experiences"
                        },
                        new
                        {
                            BookId = 64,
                            AuthorId = 74,
                            BasePrice = 27.184798688297590m,
                            PublishDate = new DateTime(2018, 8, 17, 12, 48, 51, 254, DateTimeKind.Local).AddTicks(5015),
                            Title = "expedite compelling models"
                        },
                        new
                        {
                            BookId = 65,
                            AuthorId = 84,
                            BasePrice = 29.116707992789755m,
                            PublishDate = new DateTime(2018, 5, 29, 0, 18, 52, 447, DateTimeKind.Local).AddTicks(1762),
                            Title = "architect back-end ROI"
                        },
                        new
                        {
                            BookId = 66,
                            AuthorId = 16,
                            BasePrice = 55.770501375424090m,
                            PublishDate = new DateTime(2021, 9, 26, 3, 37, 39, 47, DateTimeKind.Local).AddTicks(7719),
                            Title = "transform extensible paradigms"
                        },
                        new
                        {
                            BookId = 67,
                            AuthorId = 55,
                            BasePrice = 72.532881049461525m,
                            PublishDate = new DateTime(2015, 12, 2, 23, 37, 11, 125, DateTimeKind.Local).AddTicks(5648),
                            Title = "aggregate robust paradigms"
                        },
                        new
                        {
                            BookId = 68,
                            AuthorId = 97,
                            BasePrice = 63.668458183343095m,
                            PublishDate = new DateTime(2015, 6, 25, 14, 7, 39, 610, DateTimeKind.Local).AddTicks(7666),
                            Title = "repurpose cross-media content"
                        },
                        new
                        {
                            BookId = 69,
                            AuthorId = 64,
                            BasePrice = 34.444452322037365m,
                            PublishDate = new DateTime(2018, 3, 18, 15, 31, 43, 902, DateTimeKind.Local).AddTicks(3632),
                            Title = "integrate next-generation systems"
                        },
                        new
                        {
                            BookId = 70,
                            AuthorId = 47,
                            BasePrice = 60.55712298431440m,
                            PublishDate = new DateTime(2023, 7, 3, 0, 34, 59, 108, DateTimeKind.Local).AddTicks(540),
                            Title = "disintermediate B2C e-markets"
                        },
                        new
                        {
                            BookId = 71,
                            AuthorId = 26,
                            BasePrice = 10.189082295526315m,
                            PublishDate = new DateTime(2017, 10, 5, 8, 44, 43, 768, DateTimeKind.Local).AddTicks(1930),
                            Title = "extend strategic methodologies"
                        },
                        new
                        {
                            BookId = 72,
                            AuthorId = 15,
                            BasePrice = 96.001719997900295m,
                            PublishDate = new DateTime(2015, 12, 31, 16, 31, 55, 606, DateTimeKind.Local).AddTicks(9499),
                            Title = "grow front-end blockchains"
                        },
                        new
                        {
                            BookId = 73,
                            AuthorId = 33,
                            BasePrice = 22.312216858831830m,
                            PublishDate = new DateTime(2018, 12, 25, 20, 15, 52, 518, DateTimeKind.Local).AddTicks(7651),
                            Title = "transition cross-platform mindshare"
                        },
                        new
                        {
                            BookId = 74,
                            AuthorId = 83,
                            BasePrice = 48.162125601227560m,
                            PublishDate = new DateTime(2014, 12, 16, 0, 6, 37, 703, DateTimeKind.Local).AddTicks(6371),
                            Title = "harness clicks-and-mortar web-readiness"
                        },
                        new
                        {
                            BookId = 75,
                            AuthorId = 51,
                            BasePrice = 26.008567819381195m,
                            PublishDate = new DateTime(2015, 7, 26, 18, 36, 8, 722, DateTimeKind.Local).AddTicks(7417),
                            Title = "monetize ubiquitous eyeballs"
                        },
                        new
                        {
                            BookId = 76,
                            AuthorId = 89,
                            BasePrice = 30.218368293754640m,
                            PublishDate = new DateTime(2020, 2, 20, 19, 37, 4, 940, DateTimeKind.Local).AddTicks(5213),
                            Title = "visualize virtual functionalities"
                        },
                        new
                        {
                            BookId = 77,
                            AuthorId = 14,
                            BasePrice = 52.207169608699140m,
                            PublishDate = new DateTime(2019, 4, 8, 2, 51, 36, 642, DateTimeKind.Local).AddTicks(4674),
                            Title = "leverage B2C e-commerce"
                        },
                        new
                        {
                            BookId = 78,
                            AuthorId = 15,
                            BasePrice = 76.361713520950695m,
                            PublishDate = new DateTime(2021, 2, 26, 5, 40, 46, 833, DateTimeKind.Local).AddTicks(2281),
                            Title = "deliver efficient relationships"
                        },
                        new
                        {
                            BookId = 79,
                            AuthorId = 13,
                            BasePrice = 43.87845665300740m,
                            PublishDate = new DateTime(2022, 11, 24, 1, 30, 4, 518, DateTimeKind.Local).AddTicks(3811),
                            Title = "syndicate open-source synergies"
                        },
                        new
                        {
                            BookId = 80,
                            AuthorId = 83,
                            BasePrice = 9.5214601086555295m,
                            PublishDate = new DateTime(2014, 12, 8, 9, 2, 54, 127, DateTimeKind.Local).AddTicks(5657),
                            Title = "productize innovative users"
                        },
                        new
                        {
                            BookId = 81,
                            AuthorId = 98,
                            BasePrice = 16.556940431420745m,
                            PublishDate = new DateTime(2020, 2, 28, 20, 12, 9, 472, DateTimeKind.Local).AddTicks(3350),
                            Title = "transform frictionless channels"
                        },
                        new
                        {
                            BookId = 82,
                            AuthorId = 34,
                            BasePrice = 28.073061571679270m,
                            PublishDate = new DateTime(2015, 6, 12, 6, 17, 19, 434, DateTimeKind.Local).AddTicks(5924),
                            Title = "disintermediate intuitive e-tailers"
                        },
                        new
                        {
                            BookId = 83,
                            AuthorId = 35,
                            BasePrice = 34.325160641222820m,
                            PublishDate = new DateTime(2022, 12, 17, 13, 48, 31, 878, DateTimeKind.Local).AddTicks(5178),
                            Title = "envisioneer 24/7 e-commerce"
                        },
                        new
                        {
                            BookId = 84,
                            AuthorId = 72,
                            BasePrice = 96.33774888783880m,
                            PublishDate = new DateTime(2017, 9, 18, 15, 20, 49, 947, DateTimeKind.Local).AddTicks(1314),
                            Title = "exploit next-generation functionalities"
                        },
                        new
                        {
                            BookId = 85,
                            AuthorId = 88,
                            BasePrice = 37.255142243280390m,
                            PublishDate = new DateTime(2020, 4, 25, 11, 55, 4, 496, DateTimeKind.Local).AddTicks(8400),
                            Title = "orchestrate one-to-one paradigms"
                        },
                        new
                        {
                            BookId = 86,
                            AuthorId = 66,
                            BasePrice = 36.72977840935645m,
                            PublishDate = new DateTime(2018, 11, 26, 4, 37, 55, 860, DateTimeKind.Local).AddTicks(7312),
                            Title = "engineer enterprise deliverables"
                        },
                        new
                        {
                            BookId = 87,
                            AuthorId = 90,
                            BasePrice = 7.6390102126277985m,
                            PublishDate = new DateTime(2019, 7, 5, 2, 13, 1, 335, DateTimeKind.Local).AddTicks(4875),
                            Title = "aggregate leading-edge initiatives"
                        },
                        new
                        {
                            BookId = 88,
                            AuthorId = 81,
                            BasePrice = 92.224620493422580m,
                            PublishDate = new DateTime(2015, 1, 15, 20, 28, 43, 131, DateTimeKind.Local).AddTicks(4618),
                            Title = "envisioneer world-class applications"
                        },
                        new
                        {
                            BookId = 89,
                            AuthorId = 27,
                            BasePrice = 70.906194160631435m,
                            PublishDate = new DateTime(2022, 8, 11, 10, 37, 52, 10, DateTimeKind.Local).AddTicks(6521),
                            Title = "implement mission-critical synergies"
                        },
                        new
                        {
                            BookId = 90,
                            AuthorId = 69,
                            BasePrice = 68.484221928046845m,
                            PublishDate = new DateTime(2018, 5, 14, 3, 29, 56, 410, DateTimeKind.Local).AddTicks(5854),
                            Title = "deploy turn-key architectures"
                        },
                        new
                        {
                            BookId = 91,
                            AuthorId = 1,
                            BasePrice = 22.384118139324370m,
                            PublishDate = new DateTime(2023, 7, 22, 23, 49, 28, 156, DateTimeKind.Local).AddTicks(772),
                            Title = "benchmark ubiquitous methodologies"
                        },
                        new
                        {
                            BookId = 92,
                            AuthorId = 73,
                            BasePrice = 59.733761191810990m,
                            PublishDate = new DateTime(2021, 3, 8, 12, 6, 34, 644, DateTimeKind.Local).AddTicks(6902),
                            Title = "expedite sexy interfaces"
                        },
                        new
                        {
                            BookId = 93,
                            AuthorId = 72,
                            BasePrice = 90.457665080398155m,
                            PublishDate = new DateTime(2015, 7, 3, 8, 36, 9, 196, DateTimeKind.Local).AddTicks(4648),
                            Title = "grow impactful synergies"
                        },
                        new
                        {
                            BookId = 94,
                            AuthorId = 100,
                            BasePrice = 37.132701996032265m,
                            PublishDate = new DateTime(2021, 2, 21, 14, 51, 4, 315, DateTimeKind.Local).AddTicks(5208),
                            Title = "leverage scalable architectures"
                        },
                        new
                        {
                            BookId = 95,
                            AuthorId = 100,
                            BasePrice = 29.615689051181375m,
                            PublishDate = new DateTime(2020, 7, 11, 13, 46, 57, 883, DateTimeKind.Local).AddTicks(9281),
                            Title = "synergize back-end web services"
                        },
                        new
                        {
                            BookId = 96,
                            AuthorId = 22,
                            BasePrice = 27.427251805660375m,
                            PublishDate = new DateTime(2020, 3, 31, 7, 6, 6, 641, DateTimeKind.Local).AddTicks(6366),
                            Title = "whiteboard revolutionary metrics"
                        },
                        new
                        {
                            BookId = 97,
                            AuthorId = 48,
                            BasePrice = 59.115475826742210m,
                            PublishDate = new DateTime(2014, 7, 6, 18, 54, 1, 322, DateTimeKind.Local).AddTicks(8996),
                            Title = "incubate next-generation interfaces"
                        },
                        new
                        {
                            BookId = 98,
                            AuthorId = 18,
                            BasePrice = 17.000586731085720m,
                            PublishDate = new DateTime(2014, 10, 17, 3, 37, 55, 601, DateTimeKind.Local).AddTicks(9452),
                            Title = "iterate holistic communities"
                        },
                        new
                        {
                            BookId = 99,
                            AuthorId = 81,
                            BasePrice = 49.252794253192735m,
                            PublishDate = new DateTime(2020, 10, 7, 8, 38, 4, 719, DateTimeKind.Local).AddTicks(7849),
                            Title = "engage integrated relationships"
                        },
                        new
                        {
                            BookId = 100,
                            AuthorId = 44,
                            BasePrice = 6.5682432309173285m,
                            PublishDate = new DateTime(2019, 2, 18, 9, 28, 22, 161, DateTimeKind.Local).AddTicks(9034),
                            Title = "repurpose revolutionary bandwidth"
                        });
                });

            modelBuilder.Entity("PublisherDomain.Cover", b =>
                {
                    b.Property<int>("CoverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoverId"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("DesignIdeas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DigitalOnly")
                        .HasColumnType("bit");

                    b.HasKey("CoverId");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("Covers");
                });

            modelBuilder.Entity("ArtistCover", b =>
                {
                    b.HasOne("PublisherDomain.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistsArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublisherDomain.Cover", null)
                        .WithMany()
                        .HasForeignKey("CoversCoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PublisherDomain.Book", b =>
                {
                    b.HasOne("PublisherDomain.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("PublisherDomain.Cover", b =>
                {
                    b.HasOne("PublisherDomain.Book", "Book")
                        .WithOne("Cover")
                        .HasForeignKey("PublisherDomain.Cover", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("PublisherDomain.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("PublisherDomain.Book", b =>
                {
                    b.Navigation("Cover")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
